// <auto-generated />
using Capstone1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Capstone1.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("Shared.Models.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<long>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = "4b10ae32-133c-4de1-8e2a-fa8b1ac5fca9",
                            Description = "Private Panio Lessons",
                            Price = 18L,
                            Title = "Private Piano Lessons (0 to 4 Years)"
                        },
                        new
                        {
                            Id = "a451ec1c-a5dc-4fea-a671-0374cf9b9894",
                            Description = "PreSchool Piano Foundation",
                            Price = 18L,
                            Title = "PreSchool Piano Foundation (2 to 4 Years)"
                        },
                        new
                        {
                            Id = "8e812948-eac1-4aec-b740-8d3265cfe3df",
                            Description = "Early Years Music",
                            Price = 18L,
                            Title = "Early Years Music"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
